/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
<<<<<<< HEAD
    "aws_cognito_identity_pool_id": "eu-north-1:4938e9e0-3d2a-4979-8392-73be72af4efd",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_b0vwExGOA",
    "aws_user_pools_web_client_id": "26vhn57jv3890s635tp7i12enk",
=======
    "aws_cognito_identity_pool_id": "eu-north-1:bb1efbb0-cce8-4671-a4f3-c73e80755a64",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_dS5mBE7DN",
    "aws_user_pools_web_client_id": "5f3ipg6gen8fapv4tnc9t3ok3v",
>>>>>>> 1347323 (local environment changes)
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
<<<<<<< HEAD
        "passwordPolicyMinLength": 8,
=======
        "passwordPolicyMinLength": " 8",
>>>>>>> 1347323 (local environment changes)
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_UPPERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
